### ISSUE TITLE
Add a new CI pipeline to test FLUO and Rook Ceph

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1000]

**Comment by invidian** [comment]
How is it different from #959 and #894? Also why one aggregate issue instead of two?

**Comment by surajssd** [comment]
This to put them together in one pipeline. Those are individual things to do that will be triggered by the pipeline created in this issue.

So both of them are blocked on this.

**Comment by invidian** [comment]
Why do they need to be in a separate pipeline then?

**Comment by surajssd** [comment]
Because in a normal pipeline this can disturb other tests as we have seen previously. I had a chat with @iaguis about this offline IIRC.

**Comment by invidian** [comment]
Hm, we already have a concept of disruptive tests in our e2e framework, do we need another one? Disruptive tests should run serially and they can do whatever they want with the cluster, as long they revert the changes back to the original state before they finish (so next test can run too).

IMO we could have one node for testing OpenEBS and 3 nodes for Ceph (if that's really needed, can't be stretch it a bit and run Ceph on just one for testing?). I'm afraid about that number of pipelines and dividing test code between them will create hard to maintain solution. I prefer to have one, slower pipeline which does all (as pipelines are already slow), rather than multiple, which only does part of the job.

**Comment by surajssd** [comment]
How do you propose to test FLUO?

**Comment by invidian** [comment]
>How do you propose to test FLUO?

- To begin the test, all nodes should have updates disabled in FLUO via label/annotation.
- Then we could either run a cluster with Flatcar version specified (latest - 1) OR we could re-configure node to use higher version channel (stable -> beta or stable -> alpha).
- In test code, we trigger an update (either via pod or via removal of label) and we wait until node gets drained, updated and rebooted.
- Test should verify, that node came back and have different Flatcar version now.

**Comment by surajssd** [comment]
- A pipeline is added and is functional.
- Tests for rook-ceph are here: https://github.com/kinvolk/lokomotive/pull/1084
- WIP tests for FLUO.

**Comment by iaguis** [comment]
Can this be closed now that https://github.com/kinvolk/lokomotive/pull/1142 is merged?
