### ISSUE TITLE
`lokoctl cluster apply` fails using S3 backend

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1016]
Other person created a cluster and shared lokocfg file with me. When I run `lokoctl cluster apply -v` it fails with following error:

```bash
...
module.dns.aws_route53_record.apiserver_public: Refreshing state... [id=XXXXXXXXXXXXXX_foobar-demo-foobar.net._A]

Error: Invalid index

  on ../terraform-modules/bootkube/outputs.tf line 95, in output "bootstrap-secrets_values":
  95:   value = var.enable_tls_bootstrap ? local_file.bootstrap-secrets[0].content : ""
    |----------------
    | local_file.bootstrap-secrets is empty tuple

The given key does not identify an element in this collection value.

Releasing state lock. This may take a few moments...
FATA[0042] Failed to reconcile cluster state: failed checking execution status: exit status 1  args="[]" command="lokoctl cluster apply"
```

The cluster is created with lokoctl version `v0.4.1`. And I can reproduce the error with 0.4.1 and current master.

**Comment by invidian** [comment]
The solution for it is to use `locals` to save value of `local_file.bootstrap-secrets[0].content` and to use `local` in `value =` instead of `local_file` reference.

This happens because if you remove assets directory, `len(local_file.bootstrap-secrets)` will be 0 after Terraform refreshes the state.
