### ISSUE TITLE
"lokoctl version" does not work with "go get" command suggested by README.md

### ISSUE THREAD

**Issue by alban** [kinvolk/lokomotive#118]
The README.md suggests:
```
go get github.com/kinvolk/lokomotive/cmd/lokoctl
```

But if we don't use make, then `lokoctl version` does not work because we don't have `LDFLAGS := "-X ...Version=$(VERSION)...`.

One possibility is to pass ldflags in the `go get` command:
```
$ CGO_ENABLED=0 go get -ldflags "-X github.com/kinvolk/lokomotive/pkg/version.Version=$(date +%Y%m%d%H%M%S) -extldflags '-static'" github.com/kinvolk/lokomotive/cmd/lokoctl
$ lokoctl version
20200309143917
```

But it is prone to errors. There might be better options with [debug.ReadBuildInfo()](https://stackoverflow.com/questions/38087256/dynamic-version-from-git-with-go-get).

**Comment by iaguis** [comment]
I'm reworking the README in #51 but in any case we also suggest running "go get" in [docs/installer/lokoctl.md](https://github.com/kinvolk/lokomotive/blob/1c84fa7e98d51b2709d2171068d3cdc7c9967817/docs/installer/lokoctl.md) as one of the options to get lokoctl.

It seems debug.ReadBuildInfo() doesn't really work for the main binary version, it only works for dependencies. Trying to run it shows `(devel)` as version of the main package:

```
$ ./lokoctl version
lokoctl: {github.com/kinvolk/lokomotive (devel)  <nil>}
{ (devel)  <nil>}
{github.com/BurntSushi/toml v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ= <nil>}
{github.com/MakeNowJust/heredoc v1.0.0 h1:cXCdzVdstXyiTqTvfqk9SDHpKNjxuom+DOlyEeQ4pzQ= <nil>}
{github.com/Masterminds/goutils v1.1.0 h1:zukEsf/1JZwCMgHiK3GZftabmxiCw4apj3a28RPBiVg= <nil>}
{github.com/Masterminds/semver/v3 v3.0.3 h1:znjIyLfpXEDQjOIEWh+ehwpTU14UzUPub3c3sm36u14= <nil>}
{github.com/Masterminds/sprig/v3 v3.0.2 h1:wz22D0CiSctrliXiI9ZO3HoNApweeRGftyDN+BQa3B8= <nil>}
{github.com/PuerkitoBio/purell v1.1.1 h1:WEQqlqaGbrPkxLJWfBwQmfEAE1Z7ONdDLqrN38tNFfI= <nil>}
{github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578 h1:d+Bc7a5rLufV/sSk/8dngufqelfh6jnri85riMAaF/M= <nil>}
...
```

Maybe we can document that using "go get" is not recommended because it doesn't populate the version or just remove it from the docs.

**Comment by invidian** [comment]
If we could embed the version for the releases, then `go get` would fetch the latest release then, which would have proper version. And building with `make` may still override it with more specific commit.

**Comment by iaguis** [comment]
After https://github.com/kinvolk/lokomotive/pull/147 and after we do the first release. `go get` will get the latest tag, so things would work fine IIUC.

**Comment by iaguis** [comment]
```bash
$ go get github.com/kinvolk/lokomotive/cmd/lokoctl
$ $GOPATH/bin/lokoctl version
0.1.0
```

Closing.
