### ISSUE TITLE
Add a way to configure extra flags for the API server

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#122]
Users might want to use k8s features not enabled by default. We should consider having a supported way to add extra flags to the API server.

**Comment by invidian** [comment]
Should this issue be labeled as `feature`, not as a `bug`? That seems like an extra functionality to me.

I see following ways of addressing it:
- Ideally, we could have some kind of interaction between cluster configuration, where installed component can inject required flags to cluster components. On the other hand, maybe it's not worth the effort, if dex+gangway is the only case, which would require such modification.
- Another approach would be to expose required parameters in the user-friendly form, so the boilerplate parameters can be hidden from the user.
- The simplest and perhaps the most flexible way of solving that would be to just allow user to specify any extra kube-apiserver flags and just advice them to use this feature. However, this implementation won't prevent users from specifying bad flags, which may affect cluster creation etc, so we need to be careful with it.

Another potential blocker I see, is #123. TL; DR with our current implementation, the work for adding this functionality will have to be done for each platform separately. Ideally we should have that only in one place.

**Comment by iaguis** [comment]
> Should this issue be labeled as `feature`, not as a `bug`? That seems like an extra functionality to me.

It is both IMO, I labeled it as a bug because currently updates break authentication setups.

**Comment by rata** [comment]
I think the third option will be needed anyways (for this or for power users being able to tune some flags or features). I'd say we can start by doing at least that :)

**Comment by rata** [comment]
I'd even consider this for the current release, if possible

**Comment by invidian** [comment]
Created PR: https://github.com/kinvolk/lokomotive/pull/182.

**Comment by iaguis** [comment]
We will allow dex+gangway configuration without exposing extra flags for now. This will be part of https://github.com/kinvolk/lokomotive/issues/123.

We might want to expose extra flags later so let's keep this issue.

**Comment by rata** [comment]
Thinking about this more, I think I changed my mind a little bit about this, sorry :-/.

I think we need insight from the product perspective. We want do add this **if** we want this in the "product". Basically, the less knobs you have, the simpler it is to test and to guarantee updates will work. And if we want this, how exactly (from a product point of view).

There might be a compromise between adding it and not, like adding it and saying it is unsupported and you need to run something that makes it obvious to use it, `lokoctl cluster apply --use-unsupported-flags-i-wont-complain-if-it-doesn't-work`(not proposing the flag, just to make a point of something really obvious). But is not realistic to support this flag and test for all possible values here not guarantee that it will work. Furthermore, some flags the user adds might break when we add new flags in new releases (if those flags are mutually exclusive, for example). So, if we want to add this, I'm not sure we can add it without a very explicit warning that everything you specify here might break on upgrades and better open a feature request to add a specific config that enables that flag instead of using this field. Probably the same applies for the kubelet.

I'm posting now and not before because I thought it was not scheduled (I don't see a milestone attached) and saw activity. My intention is to agree on what needs to be done. Just wanted to get together and clarify as soon as possible (I see some commits mentioning this bug yesterday) what should be done here, so we agree in advance.

cc @iaguis regarding product insight, that IMHO is needed, to see if and how we want to support this.

What do others think?

**Comment by iaguis** [comment]
We haven't decided if we want this. I added a comment to https://github.com/kinvolk/lokomotive/pull/182#issuecomment-627416188 to clarify.

**Comment by rata** [comment]
@iaguis thanks! Sorry, I didn't read the PR :see_no_evil:

**Comment by invidian** [comment]
Do we still want to allow setting arbitrary flags for kube-apiserver?

**Comment by iaguis** [comment]
> Do we still want to allow setting arbitrary flags for kube-apiserver?

We haven't decided yet. Personally I'd rather delay this until there's user demand.

**Comment by iaguis** [comment]
Let's close this. If there's demand a new issue can be opened.
