### ISSUE TITLE
Create PoC operator to reconcilate components from CRDs

### ISSUE THREAD

**Issue by rata** [kinvolk/lokomotive#1272]
**Current situation**
Components are installed via lokoctl only

**Ideal future situation**
Components are installed automatically by an in-cluster operator that reads the desired state from CRDs.

**Implementation options**
The idea is to create the plumbing/building blocks to improve later for the operator, like the skeleton for CRDs we will use for components, define metadata section of CRDs if that makes sense, etc.

This PoC should be able to install one component of your choice, based on the CRDs created.  Some suggested limitations to have on this PoC, but feel free to ignore them and use the limitations that you think make sense for the PoC:
 * It is totally okay if some modifications to the CRD don't reflect in the installed component (i.e. if changing some field on the CRD that ends up in a configmap and the pods are not restarted to take the new configmap at this stage is totally fine).
 * It is okay too to assume the helm chart to apply is on the filesystem this operator is running.
 * Not handle component upgrades for now, or the manual steps we currently need to do in any way

The CRDs for the component created should use the CRDs validation functionality to validate that a valid config is written to the CRD. It will be interesting if, while working on this, you find any limitations for CRDs validations that might be an issue in the future.

Ideally, reuse current lokomotive structs for component configuration

Additionally, please create a list of curated links for anyone to jump into this task and be up to speed. For example, doc to read about CRDs, general documentation about the design you chose, documentation you think interesting to read about the framework used (if any), etc.

**Sorry if this seems under-specified**, I lack the information to specify it on more detail. I expect that solving this should give us more context about CRDs and what makes sense to do or don't.

**Comment by knrt10** [comment]
I did research on some of it, I think we could use https://github.com/operator-framework/operator-sdk. This can be used to create the autogenerated go code for our operator initially. So the steps can be followed like this

- Create a schema for CRDs that can handle the installation for component.
- genererate go code for handling CRDs.
- deploy the operator while bootstrapping. But for testing, it can be done using a simple YAML file with an image build locally from the above go code.
- have a schema for CRDs to install the component with options that we want. Initially, we should start with simple components i.e without having any options to specify.

I will try to test it using the above steps on `httpbin` component

**Comment by invidian** [comment]
@knrt10 also check out kube-builder. While working on CAPI I found that it's quite low touch and provides nice way to generate CRDs too.

**Comment by knrt10** [comment]
### **Updates**

I have successfully done POC on installing/deleting components on L8e using CRs.

### Initial blockers

First I experimented with `kube-builder` but their latest release at that time used `client-go` packages of version `0.17.2`. We wanted to have some latest API features as we were already using `v0.18.0`, so I switched back to `operator-sdk`. Now the next blocker was our Helm fork https://github.com/kinvolk/helm/ was not updated. Due to which the operator could not build code and run. So  @invidian helped me for rebasing the code, now we have updated the fork on top of the latest Helm release at that time I.e `v3.5.1` https://github.com/kinvolk/helm/tree/knrt10/v3.5.1-rollback

### How to run the operator

I have pushed the code on `knrt10/l8e-operator-component-install` branch. Also, the documentation can be found here. https://github.com/kinvolk/lokomotive/tree/knrt10/l8e-operator-component-install/lokomotive-operator

**Comment by knrt10** [comment]
POC is done, so closing in favour of https://github.com/kinvolk/lokomotive/issues/1366
