### ISSUE TITLE
Consider supporting AWS spot instances for controller nodes

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#174]
Currently we support AWS spot instances for worker pools but not for controller nodes.

We should consider whether supporting spot instances for controller nodes makes sense.

**Comment by rata** [comment]
I don't think it makes sense for production. I've run 100% of workers on spot instances for several years, and cost-wise the trade-off was not worth it for controllers (you can just reserve those, you normally don't need to change the instance type of controllers, as you normally use the same controller instance type to handle clusters from 10 nodes to ~100 nodes).

It **might** make sense for our CI to use spot for controllers (specially if we use spot instance types that are guaranteed to live for at least X hours) or setups alike, but I honestly don't see it useful in production.

Also, this is not trivial to add for controllers now. For workers this is trivial because we are using ASG, but for controllers we aren't (we probably should, though), and therefore is not easy to add.

So, I'd say we don't add it now, if ourselves or other users see the need, they can re-open the issue or create a new one for this.

cc @invidian that suggested the issue in #149  

PS: This maybe leads to an infinite loop in after X more issues are created, but it might make sense to create an issue to use ASGs for controllers on AWS :joy:

**Comment by invidian** [comment]
Created https://github.com/kinvolk/lokomotive/issues/178 for ASGs for controllers on AWS.

Thanks for the explanation @rata, I think it make sense to close it for now then, if @blixtra agrees, as he was the OP of spot-instances issue.

**Comment by iaguis** [comment]
Let's close this for now.

**Comment by blixtra** [comment]
> It **might** make sense for our CI to use spot for controllers (specially if we use spot instance types that are guaranteed to live for at least X hours) or setups alike, but I honestly don't see it useful in production.

I was only referring to the CI scenario.
