### ISSUE TITLE
Expose read-only CI results to everyone

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#2]
We want to have a read-only view of the CI results exposed to the public so they can see the results of the CI test.

**Comment by johananl** [comment]
I've been working on a new CI platform for the project. This work is now done and I can begin migrating the pipelines to the new platform.
Once migrated, we can wait a few days to gain confidence in the new platform, then we can expose the pipelines to the public (the operation is a single command per pipeline).

**Comment by iaguis** [comment]
Cool, looking forward to it.

**Comment by johananl** [comment]
The new CI platform (http://yard.lokomotive-k8s.net/) is up and running. The platform itself is already exposed to the internet and is (hopefully) fairly secure.

The only remaining task for this issue is ensuring the output of all pipelines doesn't contain secrets. I've already checked https://github.com/kinvolk/lokomotive-ci/blob/master/lokomotive-oss-master.yaml and marked the job inside the pipeline as `public: true` (which doesn't actually expose the pipeline but rather *allows* anonymous users to see the job's output when the pipeline is exposed using `fly expose-pipeline`).

**Comment by johananl** [comment]
The new CI platform (http://yard.lokomotive-k8s.net/) is up and running. The platform itself is already exposed to the internet and is (hopefully) fairly secure.

The only remaining task for this issue is ensuring the output of all pipelines doesn't contain secrets. I've already checked the pipeline which builds `master`.

**Comment by iaguis** [comment]
Created https://github.com/kinvolk/lokomotive/issues/267 to track checking secrets.
