### ISSUE TITLE
Make linting faster

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#391]
Right now linting takes about 90 seconds on my laptop (using `make lint-docker`). This doesn't sound like much, however it is IMO quite long for a static analysis tool. If we want to run the linter as part of our dev workflow (namely after every code change), we should try to make it faster.

On the CI linting takes about 12 seconds, however it's not so nice to push your code only to get shouted at a minute later, i.e. I think we want to run it locally. If it's fast enough, we can run it always as part of `make`.

**Comment by invidian** [comment]
@johananl there is also `make lint` available, if you have `golangci-lint` installed locally. The disadvantage of it is, that you need to have it installed locally obviously and sometimes, there are some issues related to `git` configuration (https://github.com/golangci/golangci-lint/issues/948). Also depending on which version you use, you may get slightly different results than CI.

The build in Docker is slow, because it does not cache Go build artifacts, so we could perhaps change the invocation to keep the cache somewhere, or keep the container alive after linting is finished.

**Comment by invidian** [comment]
@johananl is that still an issue for you?

**Comment by johananl** [comment]
No, after fixing the Git config `make lint` works fine for me.
