### ISSUE TITLE
Allow alertmanager Slack URL to be parameterised

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#434]
We provide alertmanager as a yaml file. And it can contain secret information like Slack URL to send the webhook request. Since this is provided as yaml we can't parameterise it like other variables in a `*.lokocfg` files.

This adds an avenue for exposing the secrets accidentally. If we can parameterise this variable then the secret information can stay in a `lokocfg.vars` file and it can be gitignored.

But now we have to `.gitignore` two configurations viz. `lokocfg.vars` and `alertmanager.yaml`.

**Comment by ipochi** [comment]
One of the ways this could be avoided is to store the alertmanager config in `lokocfg.vars` instead of a separate file.

So, instead of 
```
alertmanager_config       = file("alertmanager-config.yaml")
```

we could do:
```
variable alertmanager_config {}
.
.
.
alertmanager_config       = var.alertmanager_config
```

and the contents of the alertmanager-config.yaml to be stored in `lokocfg.vars` as

```
#lokocfg.vars
alertmanager_config=<<EOF
<contents here as per the requirements of two spaces indentation>
EOF
```

Tested the above scenario and confirm that it works.

I will open a PR to update the documentation adding a note that to avoid having to gitignore alertmanager_config.yaml, one can also use the above way.

**Comment by invidian** [comment]
Done in #570.
