### ISSUE TITLE
Parameterise the ClusterIssuers for components

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#437]
Right now we have two `ClusterIssuer` installed with cert-manager `letsencrypt-production` and `letsencrypt-staging`. But all the components that use cert-manager have hardcoded `letsencrypt-production` in their ingresses.

https://github.com/kinvolk/lokomotive/blob/9e3eaf64546c2498485a26757be5ae0cc0adf7a2/pkg/components/dex/component.go#L188
https://github.com/kinvolk/lokomotive/blob/9e3eaf64546c2498485a26757be5ae0cc0adf7a2/pkg/components/gangway/component.go#L246
https://github.com/kinvolk/lokomotive/blob/9e3eaf64546c2498485a26757be5ae0cc0adf7a2/pkg/components/httpbin/component.go#L99

Provide a variable to the user in these components to change the `ClusterIssuer`.

**Comment by invidian** [comment]
Couple of notes:
- This is to avoid hitting Let's Encrypt limits while testing. When testing, staging issuer should be used instead of production one, as it has much higher limits.
- Which one should we pick up by default? Should we provider production-ready as default and let the user fall into the limits more often while testing or be staging by default and make sure specify production deployments explicitly?
- Once implemented, CI configurations should be set to use staging certificates.
