### ISSUE TITLE
Update error wrapping to new Golang conventions

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive#59]
Since Go 1.13 there's a [new way to work with errors](https://blog.golang.org/go1.13-errors). We should go through our use of `fmt.Errorf` and `errors.Wrap*` to make sure we are following it.

**Comment by invidian** [comment]
I think eventually, we should completely get rid of `github.com/pkg/errors` as a depedency.

**Comment by invidian** [comment]
#388 addresses that.

**Comment by johananl** [comment]
While we're touching errors, I think we should properly format error strings:

- Error strings should not be capitalized (unless it's the *beginning* of the error string, i.e. the place where the error gets printed).
- Error strings should not end in a period.

I'm also not fond of things like "failed to do this and that". Since error strings are typically chained, we can skip the "failed/cloudn't/error" text and just give context:

:heavy_check_mark: `fmt.Errorf("rendering manifest: %v", err)`
:x: `fmt.Errorf("error rendering manifest: %v", err)`
:x: `fmt.Errorf("rendering manifest failed: %v", err)`
:x: `fmt.Errorf("could not render manifest: %v", err)`
:x: `fmt.Errorf("I really wanted to render this manifest but alas, I have failed: %v", err)`
