### ISSUE TITLE
Don't use logrus Fatalf() method

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#630]
`Fatalf()` after printing given message makes process exit with code 1, which can be used instead of using `return` statements in the function, which in my opinion hides the complexity of the functions. We should make functions return errors and then we can call `Fatalf()` once.

**Comment by johananl** [comment]
`Fatal()`/`Fatalf()` is typically used only in the **topmost** level of an application. Any **imported** package or library shouldn't decide to terminate the process on behalf of the caller.

In the topmost level of Lokomotive (which is `cli/cmd`) I find it OK to use `Fatal()`/`Fatalf()` since the alternative would be print + exit, which is longer.

>We should make functions return errors and then we can call Fatalf() once.

Which functions for example are we talking about?

**Comment by invidian** [comment]
>In the topmost level of Lokomotive (which is cli/cmd) I find it OK to use Fatal()/Fatalf() since the alternative would be print + exit, which is longer.

Assuming that we should almost have no code in `cli/cmd`, I agree :smile:

**Comment by invidian** [comment]
>Which functions for example are we talking about?

I'd say all functions which can be/should be unit tested.

**Comment by invidian** [comment]
This is now done. We only use `Fatalf` now where it actually make sense.
