### ISSUE TITLE
Rename PSP policies alphabetically

### ISSUE THREAD

**Issue by rata** [kinvolk/lokomotive#7]
The PSP policy order is explained here: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#policy-order

When adding a new PSP in this PR: https://github.com/kinvolk/terraform-render-bootkube/pull/15/files we hit issues were different policies were used because of the alphabetical order of the PSP names.

Therefore, the name was chosen to be first in alphabetical ordern, but is not quite clear for an Engineer and is very error prone.

We can use a format that starts with a number, like 01-xx, 02-yy, and be sure PSP order is explicit to the engineer writing them.

**Comment by johananl** [comment]
Personally I'm not fond of numbering things like rules, config files etc. I find it inflexible as you're required to predict in advance things you can't know about ("will I ever need to add a policy between `00` and `01`?").

I agree that we shouldn't have arbitrary behavior due to accidental policy selection, however my main question is - can we avoid the need to order altogether? In other words, why do we have a situation where the order matters?

**Comment by invidian** [comment]
@surajssd this is now done, right?

**Comment by surajssd** [comment]
It is done but not documented.

**Comment by invidian** [comment]
I think documentation can be tracked in #1 and #330.
